name: 'Deploy'
description: 'Build and deploy workshop'

inputs:
  flavour:
    description: type of version to release
    required: true
    default: 'minor'

outputs:
  tag_name:
    description: name of tag created by bumpversion
    value: ${{ steps.bumpversion.outputs.tag_name }}

runs:
  using: "composite"
  steps:
    - name: Bumpversion and commit
      id: bumpversion
      shell: bash
      run: ./.github/ci/do_release -t ${{ inputs.flavour }}

    - name: Build Site
      shell: bash
      run: ./.github/ci/build_site -b ${{ steps.bumpversion.outputs.base_url }} -t ${{ steps.bumpversion.outputs.tag_name }}

    - name: Prepare and publish to GitHub pages
      shell: bash
      env:
        TOKEN: ${{ github.token }}
      run: ./.github/ci/publish_release -t ${{ steps.bumpversion.outputs.tag_name }}
